export * from './Header/Header';
export * from './GenresFilmPageComponent/GenresFilmPageComponent';
export * from './GenresLinksList/GenresLinksList';
export * from './MovieDetailsPageComponent/MovieDetailsPageComponent';
export * from './SearchFilmPageComponent/SearchFilmPageComponent'
export * from './MovieCard/MovieCard';
export * from './GenreBadge/GenreBadge';
export * from './MovieInfo/MoviesInfo';
export * from './Search/Search';
export * from './Trailer/Trailer';
export * from './MoviesPageComponent/MoviesPageComponent'
export * from './Pagination/Pagination'